[workspace]
resolver = "2"
members = [
  "crates/evm",
  "crates/svm",
  "crates/extension",
  "crates/channel",
  "crates/sdk",
  "plugins/ohlc-1m",
  "plugins/erc20-transfer",
  "plugins/svm-accounts",
]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
