services:
  foundry:
    container_name: pg-chainsync-foundry
    build:
      context: .
      dockerfile: ./dev/Dockerfile.foundry
    volumes:
      - ./dev/state.anvil:/root/foundry/state.anvil:z
    ports:
      - 8545:8545
    networks:
      - net-chainsync
  database:
    container_name: pg-chainsync
    build:
      context: .
      dockerfile: ./dev/Dockerfile.db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dev/dev.sql:/docker-entrypoint-initdb.d/99_dev.sql:z
      - ./target/release/pg_chainsync-pg17/opt/postgres/pgrx-install/lib/postgresql/pg_chainsync.so:/usr/lib/postgresql/17/lib/pg_chainsync.so:z
      - ./target/release/pg_chainsync-pg17/opt/postgres/pgrx-install/share/postgresql/extension/pg_chainsync.control:/usr/share/postgresql/17/extension/pg_chainsync.control:z
      - ./target/release/pg_chainsync-pg17/opt/postgres/pgrx-install/share/postgresql/extension/pg_chainsync--0.0.0.sql:/usr/share/postgresql/17/extension/pg_chainsync--0.0.0.sql:z
    ports:
      - 5432:5432
    networks:
      - net-chainsync
    depends_on:
      - foundry
  erc20:
    container_name: pg-chainsync-erc20
    build:
      context: ./dev/erc20
      dockerfile: Dockerfile
    networks:
      - net-chainsync
    depends_on:
      - foundry
networks:
  net-chainsync:
    driver: bridge
