FROM rust:1.78-bullseye

WORKDIR /root
RUN git clone https://github.com/foundry-rs/foundry.git

WORKDIR /root/foundry
RUN cargo install --path ./crates/anvil --profile local --force --locked

ENTRYPOINT ["anvil", "--host", "0.0.0.0", "--load-state", "state.anvil"]
