FROM rust:1.88-bullseye

WORKDIR /root
RUN git clone https://github.com/foundry-rs/foundry.git --depth 2

WORKDIR /root/foundry
RUN cargo install --path ./crates/anvil --force --locked

ENTRYPOINT ["anvil", "--host", "0.0.0.0", "--load-state", "state.anvil"]
